name: Export ABIs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node ./index.js

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Automated update" || echo "No changes to commit"
          git push
